name: Stylesheet Lint
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'


jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # Install your linters here
      - uses: actions-hub/stylelint@master
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          stylelint: true
          stylelint_dir: src/
          stylelint_extensions: css,scss
