name: Stylesheet Lint
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'


jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - name: stylelinter
        uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: 4
          PATTERN: "*.css"
